name: Forever Run Test

on:
  pull_request:
    branches:
      - 'schedule/**'
  schedule:
    - cron: "0 * * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Hello
      run: echo Hello
